spring:
  application:
    name: config-server
  profiles:
    active: native
server:
  port: 8888
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
#spring.application.name=config-server
#server.port=8888
#spring.profiles.active=native